"""
Render DatabaseSchema as Markdown for LLM / human consumption.
"""

from __future__ import annotations

from collections import defaultdict
from datetime import datetime, timezone

from .collector import DatabaseSchema, ForeignKeyInfo, QueryExample, TableInfo


# Known framework table prefixes (any Django project)
FRAMEWORK_PREFIXES = (
    "django_",
    "auth_",
    "django_celery_beat_",
    "jet_",
    "south_",
)


def infer_domain(table_name: str) -> str:
    """Group tables by first underscore segment, with framework heuristics."""
    for prefix in FRAMEWORK_PREFIXES:
        if table_name.startswith(prefix):
            return "django_system"
    if "_" in table_name:
        return table_name.split("_", 1)[0]
    return "other"


def hub_tables(schema: DatabaseSchema, limit: int = 25) -> list[tuple[str, int, int | None]]:
    """Tables most often referenced by FKs (incoming), with optional row counts."""
    in_degree: dict[str, int] = defaultdict(int)
    row_by_name = {t.name: t.row_count for t in schema.tables}
    for table in schema.tables:
        for fk in table.outgoing_fks:
            in_degree[fk.to_table] += 1
    ranked = sorted(in_degree.items(), key=lambda x: (-x[1], x[0]))[:limit]
    return [(name, deg, row_by_name.get(name)) for name, deg in ranked]


class MarkdownWriter:
    def __init__(
        self,
        schema: DatabaseSchema,
        *,
        title: str | None = None,
        include_fk_index: bool = True,
        include_hub_section: bool = True,
        hub_limit: int = 25,
        project_hints: str | None = None,
    ):
        self.schema = schema
        self.title = title or f"{schema.database_name} Database Schema Reference"
        self.include_fk_index = include_fk_index
        self.include_hub_section = include_hub_section
        self.hub_limit = hub_limit
        self.project_hints = project_hints

    def write(self) -> str:
        lines: list[str] = []
        w = lines.append

        w(f"# {self.title}")
        w("")
        w(
            f"> Auto-generated by `python manage.py generate_database_doc` "
            f"| {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"
        )
        w(
            f"> Tables: {len(self.schema.tables)} | "
            f"Columns: {self.schema.column_count} | "
            f"Foreign keys: {self.schema.fk_count}"
        )
        w("")
        w("---")
        w("")
        self._section_purpose(w)
        self._section_connection(w)
        if self.project_hints:
            w("### Project notes")
            w("")
            w(self.project_hints)
            w("")
            w("---")
            w("")
        self._section_domains(w)
        if self.include_hub_section:
            self._section_hubs(w)
        self._section_toc(w)
        if self.include_fk_index:
            self._section_fk_index(w)
        self._section_tables(w)

        return "\n".join(lines) + "\n"

    def _section_purpose(self, w) -> None:
        w("## 1. Purpose and how to use this document")
        w("")
        w("This file describes the **live database schema** behind your Django project's")
        w("`DATABASES` configuration. Use it to:")
        w("")
        w("- Write correct SQL with real table and column names")
        w("- Understand relationships via foreign keys")
        w("- Navigate tables grouped by name prefix / domain")
        w("")
        w("**Conventions:**")
        w("")
        w("- Table names match the database (often `app_label_modelname` when using Django migrations).")
        w("- Column types are shown as Django field class names from introspection (e.g. `CharField`, `BigAutoField`).")
        w("- 🔑 marks primary key columns.")
        w("")
        w("---")
        w("")

    def _section_connection(self, w) -> None:
        w("## 2. Connection metadata")
        w("")
        w("| Setting | Value |")
        w("|--------|-------|")
        w(f"| Engine | `{self.schema.engine}` |")
        w(f"| Vendor | `{self.schema.vendor}` |")
        w(f"| Database | `{self.schema.database_name}` |")
        w(f"| Host | `{self.schema.host}` |")
        w(f"| Port | `{self.schema.port}` |")
        w("")
        w("Credentials come from environment variables / settings — never commit passwords.")
        w("")
        w("---")
        w("")

    def _section_domains(self, w) -> None:
        w("## 3. Domain overview")
        w("")
        domains: dict[str, list[TableInfo]] = defaultdict(list)
        for table in self.schema.tables:
            domains[infer_domain(table.name)].append(table)

        w("| Domain | Tables |")
        w("|--------|--------|")
        for dom in sorted(domains.keys(), key=lambda x: (-len(domains[x]), x)):
            w(f"| `{dom}` | {len(domains[dom])} |")
        w("")
        w("---")
        w("")

    def _section_hubs(self, w) -> None:
        w("## 4. Hub tables (most referenced by foreign keys)")
        w("")
        hubs = hub_tables(self.schema, self.hub_limit)
        if not hubs:
            w("*(No foreign keys detected.)*")
            w("")
            w("---")
            w("")
            return

        w("| Table | Referenced by | Rows |")
        w("|-------|---------------|------|")
        for name, deg, rows in hubs:
            row_s = str(rows) if rows is not None else "—"
            w(f"| `{name}` | {deg} | {row_s} |")
        w("")
        w("---")
        w("")

    def _section_toc(self, w) -> None:
        section = "5" if self.include_hub_section else "4"
        w(f"## {section}. Table of contents (by domain)")
        w("")
        domains: dict[str, list[TableInfo]] = defaultdict(list)
        for table in self.schema.tables:
            domains[infer_domain(table.name)].append(table)

        for dom in sorted(domains.keys(), key=lambda x: (-len(domains[x]), x)):
            w(f"### {dom}")
            for table in sorted(domains[dom], key=lambda t: t.name):
                anchor = table.name.lower()
                w(f"- [{table.name}](#table-{anchor})")
            w("")
        w("---")
        w("")

    def _section_fk_index(self, w) -> None:
        section = "6" if self.include_hub_section else "5"
        w(f"## {section}. Foreign key relationship index")
        w("")
        w("Outgoing foreign keys per table (`child.column` → `parent.column`).")
        w("")
        for table in self.schema.tables:
            if not table.outgoing_fks:
                continue
            w(f"### `{table.name}`")
            for fk in table.outgoing_fks:
                w(self._fk_line(fk))
            w("")
        w("---")
        w("")

    def _section_tables(self, w) -> None:
        base = 7 if self.include_hub_section else 6
        if not self.include_fk_index:
            base -= 1
        w(f"## {base}. Tables — columns, keys, indexes")
        w("")

        for table in sorted(self.schema.tables, key=lambda t: t.name):
            self._write_table(w, table)
            w("---")
            w("")

    def _write_business_context(self, w, table: TableInfo) -> None:
        biz = table.business
        if biz is None:
            return
        has_model_doc = bool(
            table.django_model and table.django_model.doc
        )
        if biz.description:
            label = (
                "**Inferred business context:**"
                if has_model_doc
                else "**Business description:**"
            )
            w(f"- {label}")
            w("")
            w(f"  {biz.description}")
            w("")
        if biz.hints:
            w("- **Business hints:**")
            w("")
            for hint in biz.hints:
                w(f"  - {hint}")
            w("")

    def _write_table(self, w, table: TableInfo) -> None:
        anchor = table.name.lower()
        dom = infer_domain(table.name)

        w(f'<a id="table-{anchor}"></a>')
        w(f"### `{table.name}`")
        w("")
        w(f"- **Domain:** `{dom}`")
        if table.django_model is not None:
            dm = table.django_model
            label = f"{dm.app_label}.{dm.model_name}"
            w(f"- **Django model:** `{label}`")
            if dm.verbose_name and dm.verbose_name != dm.model_name:
                w(f"- **Model label:** {dm.verbose_name}")
            if dm.doc:
                w("- **Business description (model):**")
                w("")
                for line in dm.doc.splitlines():
                    w(f"  {line}")
                w("")
        self._write_business_context(w, table)
        if table.primary_key:
            w(f"- **Primary key:** `{', '.join(table.primary_key)}`")
        else:
            w("- **Primary key:** *(none)*")
        if table.row_count is not None:
            w(f"- **Row count:** {table.row_count}")
        w("")

        if table.outgoing_fks:
            w("**References (outgoing):**")
            w("")
            for fk in table.outgoing_fks:
                w(self._fk_line(fk, prefix="- "))
            w("")

        if table.incoming_fks:
            w("**Referenced by (incoming):**")
            w("")
            for fk in table.incoming_fks:
                w(
                    f"- `{fk.from_table}.{fk.from_column}` → "
                    f"`{table.name}.{fk.to_column}`"
                )
            w("")

        w("**Columns:**")
        w("")
        show_django = table.django_model is not None
        if show_django:
            w("| # | Column | Django field | Label | Help | Type | Nullable | Default |")
            w("|---|--------|--------------|-------|------|------|----------|---------|")
        else:
            w("| # | Column | Type | Nullable | Default |")
            w("|---|--------|------|----------|---------|")
        for col in table.columns:
            pk = " 🔑" if col.is_primary_key else ""
            null = "YES" if col.nullable else "NO"
            default = col.default or ""
            if show_django:
                field = f"`{col.django_field}`" if col.django_field else ""
                label = col.verbose_name or ""
                help_txt = col.help_text.replace("|", "\\|") if col.help_text else ""
                w(
                    f"| {col.ordinal} | `{col.name}`{pk} | {field} | {label} | "
                    f"{help_txt} | {col.type_display} | {null} | {default} |"
                )
            else:
                w(
                    f"| {col.ordinal} | `{col.name}`{pk} | {col.type_display} "
                    f"| {null} | {default} |"
                )
        w("")

        if table.indexes:
            w("**Indexes:**")
            w("")
            for idx in table.indexes:
                uniq = "UNIQUE " if idx.unique else ""
                cols = ", ".join(idx.columns)
                w(f"- `{idx.name}` ({uniq}): {cols}")
            w("")

        self._write_query_examples(w, table)

    def _write_query_examples(self, w, table: TableInfo) -> None:
        if not table.query_examples:
            return
        w("**Query examples:**")
        w("")
        for example in table.query_examples:
            lang = "python" if example.kind == "orm" else "sql"
            w(f"- *{example.title}* ({example.kind.upper()})")
            w("")
            w(f"```{lang}")
            w(example.code)
            w("```")
            w("")

    @staticmethod
    def _fk_line(fk: ForeignKeyInfo, prefix: str = "- ") -> str:
        rules = ""
        if fk.on_delete or fk.on_update:
            parts = []
            if fk.on_delete:
                parts.append(f"ON DELETE `{fk.on_delete}`")
            if fk.on_update:
                parts.append(f"ON UPDATE `{fk.on_update}`")
            rules = " — " + ", ".join(parts)
        return (
            f"{prefix}`{fk.from_column}` → `{fk.to_table}.{fk.to_column}`{rules}"
        )
